# -*- coding: utf-8 -*-
"""PPE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Edj-8aA1dVGETAQgpPZdZWZTGR0764E_
"""

!pip install roboflow ultralytics

from google.colab import drive
drive.mount('/content/drive')

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="vgJGR0I9GkTQK66mfG3o")
project = rf.workspace("sdp-lfigk").project("ppe-detection-ozhfb")
version = project.version(14)
dataset = version.download("yolov11")

from ultralytics import YOLO

# Load a model
model = YOLO("yolo11n.pt")

from roboflow import Roboflow
from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

model.train(
    data = "/content/PPE-DETECTION-14/data.yaml",
    epochs = 150,
    imgsz = 640,
    batch = 16
)

# Chạy validation để xem bảng tổng kết chi tiết
metrics = model.val()

# In ra mAP50 cho toàn bộ mô hình và từng lớp
print(f"mAP50 toàn bộ: {metrics.box.map50:.3f}")
print(f"mAP50-95 toàn bộ: {metrics.box.map:.3f}")

def show_img(path):
    img = cv2.imread(path)
    cv2_imshow(img)

    return None

show_img("/content/runs/detect/train/results.png")

show_img("/content/runs/detect/train/confusion_matrix.png")

# ==========================================
# INFERENCE (SUY LUẬN) VỚI CAMERA TRỰC TIẾP
# ==========================================
# Phần này dùng để áp dụng thực tế sau khi huấn luyện xong.
# Lưu ý: Nếu chạy trên máy tính cá nhân (local), bạn có thể dùng show=True để hiển thị cửa sổ camera.
# Nếu chạy trên Google Colab, bạn không thể pop-up cửa sổ camera mà không dùng trick (JS).

# 1. Load trọng số mô hình tốt nhất vừa được train (thay đổi đường dẫn nếu cần)
# best_model = YOLO("/content/runs/detect/train/weights/best.pt") 

# Trong trường hợp đang chạy cùng một phiên, bạn có thể tiếp tục sử dụng biến 'model' hiện tại.

# 2. Cấu hình nguồn camera:
# - Webcam máy tính: "0" hoặc "1"
# - Camera IP (RTSP): "rtsp://username:password@dia_chi_ip:port/stream"
# - Video có sẵn: "duong_dan_den_video.mp4"
camera_source = "0" 

print(f"Bắt đầu kết nối với camera: {camera_source}")

# 3. Chạy inference dự đoán liên tục
# stream=True để xử lý stream hiệu quả (trả về generator, tiết kiệm bộ nhớ)
# show=True để hiển thị cửa sổ dự đoán trực tiếp
results = model.predict(source=camera_source, show=True, stream=True)

# Lặp qua kết quả của luồng camera/stream
for r in results:
    # Xử lý kết quả từng frame (nếu cần)
    # Ví dụ: lấy bounding boxes, lưu ảnh, v.v.
    boxes = r.boxes 
    pass